os:
  - osx

language: node_js
node_js:
  - "7"

cache:
  yarn: true
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - npm install yarn -g nps
  - yarn install

script:
  - nps webpack.build.development
  - nps release
after_success:
  - nps release

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
