osx_image: xcode7.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  - os: linux
    env: CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
install:
- nvm install 6
- npm install electron-builder@next
- npm install yarn -g
- npm install nps -g
- yarn install
script:
- nps webpack.build.development
- nps release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
