os: Visual Studio 2015

platform:
  - x64

environment:
  nodejs_version: "7"

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

branches:
  only:
    - master

skip_tags: true

version: "{build}"

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install yarn -g nps
  - yarn install

build_script:
  - nps build
  - nps release
