os: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: "7"
  SIGNTOOL: C:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe

branches:
  only:
    - master

skip_tags: true

version: "{build}"

install:
  - ps: $certSelfSigned = New-SelfSignedCertificate -DnsName trimatech.ee -CertStoreLocation Cert:\CurrentUser\My -KeyExportPolicy Exportable -Type CodeSigningCert -KeySpec Signature
  - ps: Set-AuthenticodeSignature -FilePath "$path\electron\scripts\get-foreground-window-title.ps1" -Certificate $certSelfSigned
  - ps: Set-AuthenticodeSignature -FilePath "$path\electron\scripts\get-user-idle-time.ps1" -Certificate $certSelfSigned 
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install yarn -g nps
  - cd electron
  - yarn install
  - cd ..
  - cd client
  - yarn install

build_script:
  - nps build.prod
  - cd ..
  - cd electron
  - nps build.prod
  - nps release
